/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		ElButton: typeof import("element-plus/es")["ElButton"]
		ElCard: typeof import("element-plus/es")["ElCard"]
		ElContainer: typeof import("element-plus/es")["ElContainer"]
		ElHeader: typeof import("element-plus/es")["ElHeader"]
		ElMain: typeof import("element-plus/es")["ElMain"]
		ElSpace: typeof import("element-plus/es")["ElSpace"]
		ElSwitch: typeof import("element-plus/es")["ElSwitch"]
		HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
		NavbarComp: typeof import("./src/components/NavbarComp.vue")["default"]
		RouterLink: typeof import("vue-router")["RouterLink"]
		RouterView: typeof import("vue-router")["RouterView"]
	}
}
